# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=512, unique=True)),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('phone_number', models.TextField(blank=True, default='')),
                ('administrator', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='domainspy.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainRank',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainspy.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainTechnology',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='domainspy.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='domaintechnology',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='domainspy.Technology'),
        ),
        migrations.AlterUniqueTogether(
            name='domaintechnology',
            unique_together=set([('domain', 'technology')]),
        ),
        migrations.AlterUniqueTogether(
            name='domainrank',
            unique_together=set([('domain', 'date')]),
        ),
    ]
