# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainspy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='fetched',
            field=models.DateField(auto_now=True),
        ),
    ]
