# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domainspy', '0002_domain_fetched'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainURI',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=2048)),
                ('crawled', models.DateField(auto_now=True)),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='domain',
            name='description',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='fetched',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='title',
        ),
        migrations.AddField(
            model_name='domainuri',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainspy.Domain'),
        ),
        migrations.AlterUniqueTogether(
            name='domainuri',
            unique_together=set([('domain', 'uri')]),
        ),
    ]
