# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainspy', '0003_auto_20171030_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainrank',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
